name: Build & Deploy ICS

on:
  schedule:
    - cron: '0 1 * * 6'   # Sa 01:00 UTC
  workflow_dispatch: {}

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run generator
        run: |
          python smo2ics.py
          mkdir -p public
          cp horststrasse.schulmanager.ics public/horststrasse.schulmanager.ics
          cat > public/index.html <<'EOF'
          <!doctype html><meta charset="utf-8">
          <title>Horststraße Schulkalender ICS</title>
          <h1>Horststraße Schulkalender</h1>
          <p>ICS-Datei: <a href="./horststrasse.schulmanager.ics">horststrasse.schulmanager.ics</a></p>
          EOF

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: public

  deploy:
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
